python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
python3 run.py --model TailSitter --controller best_model
